export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_RESET = "LOGIN_USER_RESET";

export const VERIFY_OTP = "VERIFY_OTP";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";
export const VERIFY_OTP_ERROR = "VERIFY_OTP_ERROR";
export const VERIFY_OTP_RESET = "VERIFY_OTP_RESET";

export const OWNER_PROFILE = "OWNER_PROFILE";
export const OWNER_PROFILE_SUCCESS = "OWNER_PROFILE_SUCCESS";
export const OWNER_PROFILE_FAILURE = "OWNER_PROFILE_FAILURE";
export const OWNER_PROFILE_ERROR = "OWNER_PROFILE_ERROR";
export const OWNER_PROFILE_RESET = "OWNER_PROFILE_RESET";

export const UPDATE_OWNER_PROFILE = "UPDATE_OWNER_PROFILE";
export const UPDATE_OWNER_PROFILE_SUCCESS = "UPDATE_OWNER_PROFILE_SUCCESS";
export const UPDATE_OWNER_PROFILE_FAILURE = "UPDATE_OWNER_PROFILE_FAILURE";
export const UPDATE_OWNER_PROFILE_ERROR = "UPDATE_OWNER_PROFILE_ERROR";
export const UPDATE_OWNER_PROFILE_RESET = "UPDATE_OWNER_PROFILE_RESET";

export const ADD_PROFILE_PICTURE = "ADD_PROFILE_PICTURE";
export const ADD_PROFILE_PICTURE_SUCCESS = "ADD_PROFILE_PICTURE_SUCCESS";
export const ADD_PROFILE_PICTURE_FAILURE = "ADD_PROFILE_PICTURE_FAILURE";
export const ADD_PROFILE_PICTURE_ERROR = "ADD_PROFILE_PICTURE_ERROR";
export const ADD_PROFILE_PICTURE_RESET = "ADD_PROFILE_PICTURE_RESET";

export const OWNER_PROPERTY = "OWNER_PROPERTY";
export const OWNER_PROPERTY_SUCCESS = "OWNER_PROPERTY_SUCCESS";
export const OWNER_PROPERTY_FAILURE = "OWNER_PROPERTY_FAILURE";
export const OWNER_PROPERTY_ERROR = "OWNER_PROPERTY_ERROR";
export const OWNER_PROPERTY_RESET = "OWNER_PROPERTY_RESET";

export const PROPERTY_NEWSLETTERS_MILESTONE = "PROPERTY_NEWSLETTERS_MILESTONE";
export const PROPERTY_NEWSLETTERS_MILESTONE_SUCCESS =
  "PROPERTY_NEWSLETTERS_MILESTONE_SUCCESS";
export const PROPERTY_NEWSLETTERS_MILESTONE_FAILURE =
  "PROPERTY_NEWSLETTERS_MILESTONE_FAILURE";
export const PROPERTY_NEWSLETTERS_MILESTONE_ERROR =
  "PROPERTY_NEWSLETTERS_MILESTONE_ERROR";
export const PROPERTY_NEWSLETTERS_MILESTONE_RESET =
  "PROPERTY_NEWSLETTERS_MILESTONE_RESET";

export const PROPERTY_VIDEOS = "PROPERTY_VIDEOS";
export const PROPERTY_VIDEOS_SUCCESS = "PROPERTY_VIDEOS_SUCCESS";
export const PROPERTY_VIDEOS_FAILURE = "PROPERTY_VIDEOS_FAILURE";
export const PROPERTY_VIDEOS_ERROR = "PROPERTY_VIDEOS_ERROR";
export const PROPERTY_VIDEOS_RESET = "PROPERTY_VIDEOS_RESET";

export const OWNER_PROPERTY_DOCUMENTS = "OWNER_PROPERTY_DOCUMENTS";
export const OWNER_PROPERTY_DOCUMENTS_SUCCESS =
  "OWNER_PROPERTY_DOCUMENTS_SUCCESS";
export const OWNER_PROPERTY_DOCUMENTS_FAILURE =
  "OWNER_PROPERTY_DOCUMENTS_FAILURE";
export const OWNER_PROPERTY_DOCUMENTS_ERROR = "OWNER_PROPERTY_DOCUMENTS_ERROR";
export const OWNER_PROPERTY_DOCUMENTS_RESET = "OWNER_PROPERTY_DOCUMENTS_RESET";

export const TRANSACTIONS = "TRANSACTIONS";
export const TRANSACTIONS_SUCCESS = "TRANSACTIONS_SUCCESS";
export const TRANSACTIONS_FAILURE = "TRANSACTIONS_FAILURE";
export const TRANSACTIONS_ERROR = "TRANSACTIONS_ERROR";
export const TRANSACTIONS_RESET = "TRANSACTIONS_RESET";

export const NOTIFICATION = "NOTIFICATION";
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_FAILURE = "NOTIFICATION_FAILURE";
export const NOTIFICATION_ERROR = "NOTIFICATION_ERROR";
export const NOTIFICATION_RESET = "NOTIFICATION_RESET";


export const NEW_NOTIFICATION = "NEW_NOTIFICATION";
export const NEW_NOTIFICATION_SUCCESS = "NEW_NOTIFICATION_SUCCESS";
export const NEW_NOTIFICATION_FAILURE = "NEW_NOTIFICATION_FAILURE";
export const NEW_NOTIFICATION_ERROR = "NEW_NOTIFICATION_ERROR";
export const NEW_NOTIFICATION_RESET = "NEW_NOTIFICATION_RESET";

export const GET_ALL_RAISED_TICKETS = "GET_ALL_RAISED_TICKETS";
export const GET_ALL_RAISED_TICKETS_SUCCESS = "GET_ALL_RAISED_TICKETS_SUCCESS";
export const GET_ALL_RAISED_TICKETS_FAILURE = "GET_ALL_RAISED_TICKETS_FAILURE";
export const GET_ALL_RAISED_TICKETS_ERROR = "GET_ALL_RAISED_TICKETS_ERROR";
export const GET_ALL_RAISED_TICKETS_RESET = "GET_ALL_RAISED_TICKETS_RESET";


export const ADD_NEW_TICKET = "ADD_NEW_TICKET";
export const ADD_NEW_TICKET_SUCCESS = "ADD_NEW_TICKET_SUCCESS";
export const ADD_NEW_TICKET_FAILURE = "ADD_NEW_TICKET_FAILURE";
export const ADD_NEW_TICKET_ERROR = "ADD_NEW_TICKET_ERROR";
export const ADD_NEW_TICKET_RESET = "ADD_NEW_TICKET_RESET";

export const GET_ALL_CONVERSATIONS = "GET_ALL_CONVERSATIONS";
export const GET_ALL_CONVERSATIONS_SUCCESS = "GET_ALL_CONVERSATIONS_SUCCESS";
export const GET_ALL_CONVERSATIONS_FAILURE = "GET_ALL_CONVERSATIONS_FAILURE";
export const GET_ALL_CONVERSATIONS_ERROR = "GET_ALL_CONVERSATIONS_ERROR";
export const GET_ALL_CONVERSATIONS_RESET = "GET_ALL_CONVERSATIONS_RESET";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";
export const SEND_MESSAGE_ERROR = "SEND_MESSAGE_ERROR";
export const SEND_MESSAGE_RESET = "SEND_MESSAGE_RESET";

export const GET_CONTACT_DETAILS = "GET_CONTACT_DETAILS";
export const GET_CONTACT_DETAILS_SUCCESS = "GET_CONTACT_DETAILS_SUCCESS";
export const GET_CONTACT_DETAILS_FAILURE = "GET_CONTACT_DETAILS_FAILURE";
export const GET_CONTACT_DETAILS_ERROR = "GET_CONTACT_DETAILS_ERROR";
export const GET_CONTACT_DETAILS_RESET = "GET_CONTACT_DETAILS_RESET";

export const SUBMIT_CONTACT_FORM = "SUBMIT_CONTACT_FORM";
export const SUBMIT_CONTACT_FORM_SUCCESS = "SUBMIT_CONTACT_FORM_SUCCESS";
export const SUBMIT_CONTACT_FORM_FAILURE = "SUBMIT_CONTACT_FORM_FAILURE";
export const SUBMIT_CONTACT_FORM_ERROR = "SUBMIT_CONTACT_FORM_ERROR";
export const SUBMIT_CONTACT_FORM_RESET = "SUBMIT_CONTACT_FORM_RESET";

export const ADD_FIREBASE_TOKEN_IN_DATABASE = "ADD_FIREBASE_TOKEN_IN_DATABASE";
export const ADD_FIREBASE_TOKEN_IN_DATABASE_SUCCESS = "ADD_FIREBASE_TOKEN_IN_DATABASE_SUCCESS";
export const ADD_FIREBASE_TOKEN_IN_DATABASE_FAILURE = "ADD_FIREBASE_TOKEN_IN_DATABASE_FAILURE";
export const ADD_FIREBASE_TOKEN_IN_DATABASE_ERROR = "ADD_FIREBASE_TOKEN_IN_DATABASE_ERROR";
export const ADD_FIREBASE_TOKEN_IN_DATABASE_RESET = "ADD_FIREBASE_TOKEN_IN_DATABASE_RESET";


export const GET_OWNER_DOCUMENT_URI = "GET_OWNER_DOCUMENT_URI";
export const GET_OWNER_DOCUMENT_URI_SUCCESS = "GET_OWNER_DOCUMENT_URI_SUCCESS";
export const GET_OWNER_DOCUMENT_URI_FAILURE = "GET_OWNER_DOCUMENT_URI_FAILURE";
export const GET_OWNER_DOCUMENT_URI_ERROR = "GET_OWNER_DOCUMENT_URI_ERROR";
export const GET_OWNER_DOCUMENT_URI_RESET = "GET_OWNER_DOCUMENT_URI_RESET";